# Generated by Django 5.2.17 on 2026-09-30 12:31

import django.db.models.deletion
from django.db import migrations, models

from persistence.tenancy import tenant_scoped


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_outbox_lease"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="outboxevent",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
            ),
        ),
    ]


# Row-level security (ADR-0009): stamp tenant_id from context, force the policy.
Migration.operations += [migrations.RunSQL(*tenant_scoped(t)) for t in ('notifications_outboxevent',)]
