# Generated by Django 5.2.17 on 2026-09-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_tenant"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outboxevent",
            name="dedupe_key",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddConstraint(
            model_name="outboxevent",
            constraint=models.UniqueConstraint(
                fields=("tenant", "dedupe_key"), name="outbox_dedupe_key_unique"
            ),
        ),
    ]
