# Generated by Django 5.2.17 on 2026-09-30 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SimAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("next_sequence", models.BigIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="SimTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("txn_id", models.CharField(max_length=64, unique=True)),
                ("sequence", models.BigIntegerField()),
                ("posted_at", models.DateTimeField()),
                ("kind", models.CharField(max_length=12)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("narration", models.CharField(blank=True, default="", max_length=255)),
                ("reference", models.CharField(blank=True, default="", max_length=64)),
                (
                    "counterparty_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "counterparty_msisdn",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="txns",
                        to="simulator.simaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["account", "sequence"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account", "sequence"), name="sim_seq_unique"
                    )
                ],
            },
        ),
    ]
