# Generated by Django 5.2.17 on 2026-09-30 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("governance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "institution",
                    models.CharField(default="I&M Bank Kenya", max_length=40),
                ),
                ("account_number", models.CharField(max_length=40)),
                ("account_name", models.CharField(max_length=120)),
                (
                    "connector",
                    models.CharField(
                        choices=[
                            ("im_simulator", "I&M simulator"),
                            ("csv_upload", "Statement file upload"),
                        ],
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="KES", max_length=3)),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="external_accounts",
                        to="governance.fund",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="external_accounts",
                        to="governance.group",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PayerMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("msisdn", models.CharField(max_length=12)),
                ("confirmed_by", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="governance.group",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="governance.membership",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReconciliationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_at", models.DateTimeField(auto_now_add=True)),
                (
                    "statement_balance",
                    models.DecimalField(decimal_places=2, max_digits=18, null=True),
                ),
                ("ledger_cash", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "difference",
                    models.DecimalField(decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "member_interests",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("unattributed", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "unexplained_out",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("retained", models.DecimalField(decimal_places=2, max_digits=18)),
                ("lines_seen", models.PositiveIntegerField()),
                ("lines_unresolved", models.PositiveIntegerField()),
                ("sequence_gaps", models.JSONField(default=list)),
                ("open_alerts", models.PositiveIntegerField()),
                ("balanced", models.BooleanField()),
                (
                    "external_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reconciliations",
                        to="connectivity.externalaccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StatementLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_txn_id", models.CharField(max_length=64)),
                (
                    "sequence",
                    models.BigIntegerField(
                        help_text="The bank's order of posting, for running balances"
                    ),
                ),
                ("posted_at", models.DateTimeField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("withdrawal", "Withdrawal"),
                            ("interest", "Interest credit"),
                            ("charge", "Bank charge"),
                            ("opening", "Opening balance"),
                        ],
                        max_length=12,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("narration", models.CharField(blank=True, default="", max_length=255)),
                ("reference", models.CharField(blank=True, default="", max_length=64)),
                (
                    "counterparty_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "counterparty_msisdn",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "running_balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "external_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="connectivity.externalaccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LineResolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("attributed", "Attributed to a member"),
                            ("unattributed", "Held as unattributed"),
                            ("interest", "Interest allocated"),
                            ("charge", "Bank charge allocated"),
                            ("matched", "Matched to a mandate"),
                            ("unmatched", "No mandate: alert raised"),
                            ("explained", "Later matched to a mandate"),
                            ("opening", "Opening balance"),
                        ],
                        max_length=14,
                    ),
                ),
                ("journal_entry_id", models.BigIntegerField()),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("actor", models.CharField(default="system", max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mandate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="governance.mandate",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="governance.membership",
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resolutions",
                        to="connectivity.statementline",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            (
                                "unmatched_outflow",
                                "Money left without an approved mandate",
                            ),
                            ("recon_difference", "Ledger and bank balance differ"),
                            (
                                "statement_conflict",
                                "Bank sent conflicting data for a transaction",
                            ),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolution_note",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alerts",
                        to="governance.group",
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="connectivity.statementline",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="externalaccount",
            constraint=models.UniqueConstraint(
                fields=("institution", "account_number"), name="conn_account_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="payermapping",
            constraint=models.UniqueConstraint(
                fields=("group", "msisdn"), name="conn_payer_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="statementline",
            index=models.Index(
                fields=["external_account", "sequence"],
                name="connectivit_externa_80b94a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="statementline",
            constraint=models.UniqueConstraint(
                fields=("external_account", "bank_txn_id"), name="conn_line_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="statementline",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="conn_line_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="alert",
            constraint=models.UniqueConstraint(
                condition=models.Q(("line__isnull", False)),
                fields=("kind", "line"),
                name="conn_one_alert_per_line",
            ),
        ),
    ]
