# Generated by Django 5.2.17 on 2026-09-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor", models.CharField(max_length=120)),
                ("action", models.CharField(max_length=80)),
                ("target_type", models.CharField(max_length=60)),
                ("target_id", models.CharField(max_length=64)),
                (
                    "group_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "operation_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="audit_audit_target__59bbff_idx",
                    )
                ],
            },
        ),
    ]
