# Generated by Django 5.2.17 on 2026-09-30 09:46

import contexts.communities.domain.membership
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "segment",
                    models.CharField(
                        choices=[
                            (
                                contexts.communities.domain.membership.Segment[
                                    "SAVINGS"
                                ],
                                contexts.communities.domain.membership.Segment[
                                    "SAVINGS"
                                ],
                            ),
                            (
                                contexts.communities.domain.membership.Segment[
                                    "WELFARE"
                                ],
                                contexts.communities.domain.membership.Segment[
                                    "WELFARE"
                                ],
                            ),
                            (
                                contexts.communities.domain.membership.Segment[
                                    "COLLECTION"
                                ],
                                contexts.communities.domain.membership.Segment[
                                    "COLLECTION"
                                ],
                            ),
                        ],
                        default=contexts.communities.domain.membership.Segment[
                            "SAVINGS"
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Fund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("currency", models.CharField(default="KES", max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="funds",
                        to="communities.group",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("group", "name"), name="community_fund_name"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("chair", "chair"), ("treasurer", "treasurer"), ("secretary", "secretary"),
                                 ("member", "member")],  # historical: the Role enum was removed (ADR-0011)
                        default="member",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                contexts.communities.domain.membership.MembershipStatus[
                                    "ACTIVE"
                                ],
                                contexts.communities.domain.membership.MembershipStatus[
                                    "ACTIVE"
                                ],
                            ),
                            (
                                contexts.communities.domain.membership.MembershipStatus[
                                    "LEFT"
                                ],
                                contexts.communities.domain.membership.MembershipStatus[
                                    "LEFT"
                                ],
                            ),
                        ],
                        default=contexts.communities.domain.membership.MembershipStatus[
                            "ACTIVE"
                        ],
                        max_length=10,
                    ),
                ),
                ("member_code", models.CharField(max_length=8)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="communities.group",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.person",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "active")),
                        fields=("group", "person"),
                        name="community_one_active_membership",
                    ),
                    models.UniqueConstraint(
                        fields=("group", "member_code"),
                        name="community_member_code_unique",
                    ),
                ],
            },
        ),
    ]
