# Generated by Django 5.2.17 on 2026-09-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0002_tenant"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="group",
            constraint=models.UniqueConstraint(
                fields=("tenant",), name="community_one_group_per_tenant"
            ),
        ),
    ]
