"""Fund codes (ADR-0023): what a member adds to a pay-in reference to pay into
a fund other than the group's default. Letters only; one meaning among a
group's open funds. The new column starts empty, so the checks below find
nothing to refuse whatever tenant context they run in."""
# Generated by Django 5.2.17 on 2026-10-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0014_membership_left_at"),
        ("tenancy", "0002_existing_rows_follow_their_foreign_keys"),
    ]

    operations = [
        migrations.AddField(
            model_name="fund",
            name="code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddConstraint(
            model_name="fund",
            constraint=models.UniqueConstraint(
                models.F("group"),
                models.F("code"),
                condition=models.Q(("code__isnull", False), ("status", "open")),
                name="community_open_fund_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="fund",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("code__isnull", True),
                    ("code__regex", "^[A-Z]{2,6}$"),
                    _connector="OR",
                ),
                name="community_fund_code_letters",
            ),
        ),
    ]
