# Generated by Django 5.2.17 on 2026-09-30 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("custody_cash", "Cash at custodian"),
                            ("member_interest", "Member interest"),
                            ("unattributed_in", "Unattributed receipts"),
                            ("unexplained_out", "Unexplained outflows"),
                            ("retained", "Retained by the group"),
                        ],
                        max_length=20,
                    ),
                ),
                ("group_id", models.BigIntegerField()),
                ("fund_id", models.BigIntegerField()),
                ("member_id", models.BigIntegerField(blank=True, null=True)),
                ("external_account_id", models.BigIntegerField(blank=True, null=True)),
                ("currency", models.CharField(default="KES", max_length=3)),
                (
                    "normal_side",
                    models.CharField(
                        choices=[("D", "Debit"), ("C", "Credit")], max_length=1
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "fund_id",
                            "purpose",
                            "member_id",
                            "external_account_id",
                        ),
                        name="ledger_account_unique_key",
                        nulls_distinct=False,
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("member_id__isnull", False),
                                ("purpose", "member_interest"),
                            ),
                            models.Q(
                                models.Q(("purpose", "member_interest"), _negated=True),
                                ("member_id__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="ledger_member_interest_has_member",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("external_account_id__isnull", False),
                                ("purpose", "custody_cash"),
                            ),
                            models.Q(
                                models.Q(("purpose", "custody_cash"), _negated=True),
                                ("external_account_id__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="ledger_custody_cash_has_external_account",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=120, unique=True)),
                ("group_id", models.BigIntegerField()),
                ("fund_id", models.BigIntegerField()),
                ("kind", models.CharField(max_length=40)),
                ("memo", models.CharField(blank=True, default="", max_length=255)),
                ("cause_type", models.CharField(max_length=60)),
                ("cause_id", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reverses",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversed_by",
                        to="ledger.journalentry",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "journal entries",
            },
        ),
        migrations.CreateModel(
            name="JournalLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("D", "Debit"), ("C", "Credit")], max_length=1
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="ledger.account",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="ledger.journalentry",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["fund_id", "id"], name="ledger_jour_fund_id_782cf2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["cause_type", "cause_id"], name="ledger_jour_cause_t_2f1ee2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalline",
            index=models.Index(
                fields=["account", "entry"], name="ledger_jour_account_a9c677_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="journalline",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="ledger_line_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalline",
            constraint=models.CheckConstraint(
                condition=models.Q(("side__in", ["D", "C"])),
                name="ledger_line_side_valid",
            ),
        ),
    ]
