# Generated by Django 5.2.17 on 2026-09-30 09:46

import contexts.governance.domain.lifecycle
import contexts.governance.domain.mandate
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("communities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Constitution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("rules", models.JSONField()),
                ("adopted_by", models.CharField(max_length=120)),
                ("effective_from", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="communities.group",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_key",
                    models.CharField(blank=True, max_length=80, null=True, unique=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(default="KES", max_length=3)),
                ("purpose", models.CharField(max_length=200)),
                ("payee_name", models.CharField(max_length=120)),
                ("payee_account", models.CharField(max_length=40)),
                (
                    "allocation",
                    models.CharField(
                        choices=[("pro_rata", "pro_rata"), ("member", "member")],
                        default=contexts.governance.domain.mandate.Allocation[
                            "PRO_RATA"
                        ],
                        max_length=10,
                    ),
                ),
                ("approvers", models.CharField(max_length=10)),
                ("required_approvals", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "open"),
                            ("approved", "approved"),
                            ("rejected", "rejected"),
                            ("cancelled", "cancelled"),
                        ],
                        default=contexts.governance.domain.lifecycle.ProposalStatus[
                            "OPEN"
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "charged_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="communities.membership",
                    ),
                ),
                (
                    "constitution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="governance.constitution",
                    ),
                ),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="communities.fund",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="communities.group",
                    ),
                ),
                (
                    "proposed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="communities.membership",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mandate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        default=contexts.governance.domain.mandate.new_reference,
                        max_length=12,
                        unique=True,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(default="KES", max_length=3)),
                ("payee_name", models.CharField(max_length=120)),
                ("payee_account", models.CharField(max_length=40)),
                (
                    "allocation",
                    models.CharField(
                        choices=[("pro_rata", "pro_rata"), ("member", "member")],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("issued", "issued"),
                            ("executed", "executed"),
                            ("expired", "expired"),
                            ("cancelled", "cancelled"),
                        ],
                        default=contexts.governance.domain.lifecycle.MandateStatus[
                            "ISSUED"
                        ],
                        max_length=10,
                    ),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "executed_by_line_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                (
                    "charged_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="communities.membership",
                    ),
                ),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="communities.fund",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="communities.group",
                    ),
                ),
                (
                    "proposal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mandate",
                        to="governance.proposal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Approval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("approve", models.BooleanField()),
                ("source", models.CharField(default="app", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="communities.membership",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approvals",
                        to="governance.proposal",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="constitution",
            constraint=models.UniqueConstraint(
                fields=("group", "version"), name="gov_constitution_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="proposal",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="gov_proposal_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="proposal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("allocation", "member"), ("charged_member__isnull", False)
                    ),
                    models.Q(
                        ("allocation", "pro_rata"), ("charged_member__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="gov_proposal_allocation_consistent",
            ),
        ),
        migrations.AddIndex(
            model_name="mandate",
            index=models.Index(
                fields=["fund", "status", "amount"],
                name="governance__fund_id_730e89_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="mandate",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="gov_mandate_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="mandate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "executed"), _negated=True),
                    ("executed_by_line_id__isnull", False),
                    _connector="OR",
                ),
                name="gov_executed_mandate_has_line",
            ),
        ),
        migrations.AddConstraint(
            model_name="approval",
            constraint=models.UniqueConstraint(
                fields=("proposal", "membership"), name="gov_one_vote"
            ),
        ),
    ]
