# Generated by Django 5.2.17 on 2026-09-30 12:31

import django.db.models.deletion
from django.db import migrations, models

from persistence.tenancy import tenant_scoped


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0002_tenant"),
        ("governance", "0002_append_only"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="approval",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="constitution",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="mandate",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="request_key",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddConstraint(
            model_name="proposal",
            constraint=models.UniqueConstraint(
                fields=("tenant", "request_key"), name="gov_proposal_request_key_unique"
            ),
        ),
    ]


# Row-level security (ADR-0009): stamp tenant_id from context, force the policy.
Migration.operations += [migrations.RunSQL(*tenant_scoped(t)) for t in ('governance_constitution', 'governance_proposal', 'governance_approval', 'governance_mandate')]
