"""Waivers of a member's arrears or fines (ADR-0022), decided like a
withdrawal. Tenant-scoped with forced row-level security; votes are
append-only; a waiver is decided once and is never deleted."""
# Generated by Django 5.2.17 on 2026-10-05 15:36

import contexts.governance.domain.lifecycle
import django.db.models.deletion
from django.db import migrations, models

from persistence.postgres import append_only
from persistence.tenancy import same_tenant, tenant_keyed, tenant_scoped


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0015_fund_codes"),
        ("governance", "0007_lookups_that_rls_can_use"),
        ("tenancy", "0002_existing_rows_follow_their_foreign_keys"),
    ]

    operations = [
        migrations.CreateModel(
            name="Waiver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "owed",
                    models.CharField(
                        choices=[("arrears", "arrears"), ("fines", "fines")],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(default="KES", max_length=3)),
                ("reason", models.CharField(max_length=200)),
                ("approvers", models.CharField(max_length=10)),
                ("required_approvals", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "open"),
                            ("approved", "approved"),
                            ("rejected", "rejected"),
                            ("cancelled", "cancelled"),
                        ],
                        default=contexts.governance.domain.lifecycle.ProposalStatus[
                            "OPEN"
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "constitution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="governance.constitution",
                    ),
                ),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="communities.fund",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="communities.group",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="communities.membership",
                    ),
                ),
                (
                    "proposed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="communities.membership",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WaiverVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("approve", models.BooleanField()),
                ("source", models.CharField(default="app", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="communities.membership",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "waiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="votes",
                        to="governance.waiver",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="waiver",
            index=models.Index(
                fields=["fund", "member", "status"],
                name="governance__fund_id_9d5489_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="waiver",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="gov_waiver_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="waivervote",
            constraint=models.UniqueConstraint(
                fields=("waiver", "membership"), name="gov_one_waiver_vote"
            ),
        ),
    ]

WAIVER_RULES = """
CREATE FUNCTION governance_waiver_rules() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP <> 'UPDATE' THEN
        RAISE EXCEPTION 'waivers are never deleted' USING ERRCODE = 'restrict_violation';
    END IF;
    IF OLD.status <> 'open' OR NEW.status = 'open'
       OR (to_jsonb(NEW) - 'status' - 'decided_at') IS DISTINCT FROM (to_jsonb(OLD) - 'status' - 'decided_at') THEN
        RAISE EXCEPTION 'a waiver is decided once and otherwise never changes' USING ERRCODE = 'restrict_violation';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER governance_waiver_rules BEFORE UPDATE OR DELETE ON governance_waiver
    FOR EACH ROW EXECUTE FUNCTION governance_waiver_rules();
CREATE TRIGGER governance_waiver_rules_truncate BEFORE TRUNCATE ON governance_waiver
    FOR EACH STATEMENT EXECUTE FUNCTION governance_waiver_rules();
"""
UNDO_WAIVER_RULES = """
DROP TRIGGER IF EXISTS governance_waiver_rules_truncate ON governance_waiver;
DROP TRIGGER IF EXISTS governance_waiver_rules ON governance_waiver;
DROP FUNCTION IF EXISTS governance_waiver_rules();
"""
MEMBERSHIP = "communities_membership"
Migration.operations += [migrations.RunSQL(*sql) for sql in (
    tenant_scoped("governance_waiver"),
    tenant_scoped("governance_waivervote"),
    append_only("governance_waivervote"),
    (WAIVER_RULES, UNDO_WAIVER_RULES),
    tenant_keyed("governance_waiver"),
    same_tenant("governance_waiver", "group_id", "communities_group"),
    same_tenant("governance_waiver", "fund_id", "communities_fund"),
    same_tenant("governance_waiver", "member_id", MEMBERSHIP),
    same_tenant("governance_waiver", "proposed_by_id", MEMBERSHIP),
    same_tenant("governance_waiver", "constitution_id", "governance_constitution"),
    same_tenant("governance_waivervote", "waiver_id", "governance_waiver"),
    same_tenant("governance_waivervote", "membership_id", MEMBERSHIP),
)]
