"""Moves between a group's funds (ADR-0024), decided like a withdrawal.
Tenant-scoped with forced row-level security; votes are append-only; a
transfer is never deleted and only moves forward through its states. A
transfer can be proposed only between open funds, and neither fund can
close while a transfer naming it is still open or approved but not yet
booked (the ADR-0015 rule, extended)."""
# Generated by Django 5.2.17 on 2026-10-05 18:52

import contexts.governance.domain.lifecycle
import django.db.models.deletion
from django.db import migrations, models

from persistence.postgres import append_only
from persistence.tenancy import same_tenant, tenant_keyed, tenant_scoped


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0015_fund_codes"),
        ("governance", "0008_waivers"),
        ("tenancy", "0002_existing_rows_follow_their_foreign_keys"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_key", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("pro_rata", "pro_rata"),
                            ("member", "member"),
                            ("retained", "retained"),
                        ],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(default="KES", max_length=3)),
                ("reason", models.CharField(max_length=200)),
                ("approvers", models.CharField(max_length=10)),
                ("required_approvals", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "open"),
                            ("approved", "approved"),
                            ("rejected", "rejected"),
                            ("cancelled", "cancelled"),
                            ("booked", "booked"),
                            ("failed", "failed"),
                        ],
                        default=contexts.governance.domain.lifecycle.TransferStatus[
                            "OPEN"
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("out_entry_id", models.BigIntegerField(blank=True, null=True)),
                ("in_entry_id", models.BigIntegerField(blank=True, null=True)),
                ("failure", models.CharField(blank=True, default="", max_length=255)),
                (
                    "constitution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="governance.constitution",
                    ),
                ),
                (
                    "from_fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="communities.fund",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="communities.group",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="communities.membership",
                    ),
                ),
                (
                    "proposed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="communities.membership",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "to_fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="communities.fund",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransferVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("approve", models.BooleanField()),
                ("source", models.CharField(default="app", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="communities.membership",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="votes",
                        to="governance.fundtransfer",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="fundtransfer",
            index=models.Index(fields=["request_key"], name="gov_transfer_request_key"),
        ),
        migrations.AddIndex(
            model_name="fundtransfer",
            index=models.Index(
                fields=["status", "id"], name="governance__status_955219_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fundtransfer",
            index=models.Index(
                fields=["from_fund", "status"], name="governance__from_fu_1541b8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="fundtransfer",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="gov_transfer_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="fundtransfer",
            constraint=models.CheckConstraint(
                condition=models.Q(("from_fund", models.F("to_fund")), _negated=True),
                name="gov_transfer_two_funds",
            ),
        ),
        migrations.AddConstraint(
            model_name="fundtransfer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("member__isnull", False), ("source", "member")),
                    models.Q(
                        models.Q(("source", "member"), _negated=True),
                        ("member__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="gov_transfer_member_iff_member_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="fundtransfer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "booked"), _negated=True),
                    models.Q(
                        ("in_entry_id__isnull", False), ("out_entry_id__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="gov_booked_transfer_has_entries",
            ),
        ),
        migrations.AddConstraint(
            model_name="fundtransfer",
            constraint=models.UniqueConstraint(
                fields=("tenant", "request_key"), name="gov_transfer_request_key_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="transfervote",
            constraint=models.UniqueConstraint(
                fields=("transfer", "membership"), name="gov_one_transfer_vote"
            ),
        ),
    ]

TRANSFER_RULES = """
CREATE FUNCTION governance_transfer_rules() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP <> 'UPDATE' THEN
        RAISE EXCEPTION 'fund transfers are never deleted' USING ERRCODE = 'restrict_violation';
    END IF;
    IF NOT ((OLD.status = 'open' AND NEW.status IN ('approved', 'rejected', 'cancelled'))
            OR (OLD.status = 'approved' AND NEW.status IN ('booked', 'failed')))
       OR (to_jsonb(NEW) - 'status' - 'decided_at' - 'settled_at' - 'out_entry_id' - 'in_entry_id' - 'failure')
          IS DISTINCT FROM
          (to_jsonb(OLD) - 'status' - 'decided_at' - 'settled_at' - 'out_entry_id' - 'in_entry_id' - 'failure') THEN
        RAISE EXCEPTION 'a fund transfer is decided once, settled once, and otherwise never changes'
            USING ERRCODE = 'restrict_violation';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER governance_transfer_rules BEFORE UPDATE OR DELETE ON governance_fundtransfer
    FOR EACH ROW EXECUTE FUNCTION governance_transfer_rules();
CREATE TRIGGER governance_transfer_rules_truncate BEFORE TRUNCATE ON governance_fundtransfer
    FOR EACH STATEMENT EXECUTE FUNCTION governance_transfer_rules();

CREATE FUNCTION governance_transfer_between_open_funds() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF (SELECT status FROM communities_fund WHERE id = NEW.from_fund_id FOR SHARE) IS DISTINCT FROM 'open'
       OR (SELECT status FROM communities_fund WHERE id = NEW.to_fund_id FOR SHARE) IS DISTINCT FROM 'open' THEN
        RAISE EXCEPTION 'money moves only between open funds' USING ERRCODE = 'restrict_violation';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER governance_transfer_between_open_funds BEFORE INSERT ON governance_fundtransfer
    FOR EACH ROW EXECUTE FUNCTION governance_transfer_between_open_funds();

CREATE OR REPLACE FUNCTION governance_fund_may_close() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.status = 'closed' AND OLD.status IS DISTINCT FROM 'closed' AND (
        EXISTS (SELECT 1 FROM governance_proposal WHERE fund_id = NEW.id AND status = 'open')
        OR EXISTS (SELECT 1 FROM governance_mandate WHERE fund_id = NEW.id AND status = 'issued')) THEN
        RAISE EXCEPTION 'fund % has an open proposal or an unexecuted mandate; settle it before closing', NEW.id
            USING ERRCODE = 'restrict_violation';
    END IF;
    IF NEW.status = 'closed' AND OLD.status IS DISTINCT FROM 'closed' AND EXISTS (
        SELECT 1 FROM governance_fundtransfer WHERE NEW.id IN (from_fund_id, to_fund_id)
                                               AND status IN ('open', 'approved')) THEN
        RAISE EXCEPTION 'fund % has a fund transfer still to be decided or booked; settle it before closing', NEW.id
            USING ERRCODE = 'restrict_violation';
    END IF;
    RETURN NEW;
END $$;
"""
UNDO_TRANSFER_RULES = """
CREATE OR REPLACE FUNCTION governance_fund_may_close() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.status = 'closed' AND OLD.status IS DISTINCT FROM 'closed' AND (
        EXISTS (SELECT 1 FROM governance_proposal WHERE fund_id = NEW.id AND status = 'open')
        OR EXISTS (SELECT 1 FROM governance_mandate WHERE fund_id = NEW.id AND status = 'issued')) THEN
        RAISE EXCEPTION 'fund % has an open proposal or an unexecuted mandate; settle it before closing', NEW.id
            USING ERRCODE = 'restrict_violation';
    END IF;
    RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS governance_transfer_between_open_funds ON governance_fundtransfer;
DROP FUNCTION IF EXISTS governance_transfer_between_open_funds();
DROP TRIGGER IF EXISTS governance_transfer_rules_truncate ON governance_fundtransfer;
DROP TRIGGER IF EXISTS governance_transfer_rules ON governance_fundtransfer;
DROP FUNCTION IF EXISTS governance_transfer_rules();
"""
MEMBERSHIP = "communities_membership"
FUND = "communities_fund"
Migration.operations += [migrations.RunSQL(*sql) for sql in (
    tenant_scoped("governance_fundtransfer"),
    tenant_scoped("governance_transfervote"),
    append_only("governance_transfervote"),
    (TRANSFER_RULES, UNDO_TRANSFER_RULES),
    tenant_keyed("governance_fundtransfer"),
    same_tenant("governance_fundtransfer", "group_id", "communities_group"),
    same_tenant("governance_fundtransfer", "from_fund_id", FUND),
    same_tenant("governance_fundtransfer", "to_fund_id", FUND),
    same_tenant("governance_fundtransfer", "member_id", MEMBERSHIP),
    same_tenant("governance_fundtransfer", "proposed_by_id", MEMBERSHIP),
    same_tenant("governance_fundtransfer", "constitution_id", "governance_constitution"),
    same_tenant("governance_transfervote", "transfer_id", "governance_fundtransfer"),
    same_tenant("governance_transfervote", "membership_id", MEMBERSHIP),
)]
