# Generated by Django 5.2.17 on 2026-09-30 07:22

import django.db.models.deletion
import governance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("parties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "segment",
                    models.CharField(
                        choices=[
                            ("savings", "Savings / investment chama"),
                            ("welfare", "Welfare group or association"),
                            ("collection", "One-off collection"),
                        ],
                        default="savings",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Fund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("currency", models.CharField(default="KES", max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="funds",
                        to="governance.group",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Constitution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("rules", models.JSONField()),
                ("effective_from", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="constitutions",
                        to="governance.group",
                    ),
                ),
            ],
            options={
                "get_latest_by": "version",
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("chair", "Chair"),
                            ("treasurer", "Treasurer"),
                            ("secretary", "Secretary"),
                            ("member", "Member"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("left", "Left")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("member_code", models.CharField(max_length=8)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="governance.group",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="parties.person",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("purpose", models.CharField(max_length=200)),
                ("payee_name", models.CharField(max_length=120)),
                (
                    "payee_account",
                    models.CharField(
                        help_text="Phone number or bank account", max_length=40
                    ),
                ),
                (
                    "allocation",
                    models.CharField(
                        choices=[
                            (
                                "pro_rata",
                                "Shared by all members, in proportion to their balances",
                            ),
                            (
                                "member",
                                "Charged to one member (e.g. exit payout or loan)",
                            ),
                        ],
                        default="pro_rata",
                        max_length=10,
                    ),
                ),
                ("approvers", models.CharField(max_length=10)),
                ("required_approvals", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "charged_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="governance.membership",
                    ),
                ),
                (
                    "constitution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="governance.constitution",
                    ),
                ),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proposals",
                        to="governance.fund",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proposals",
                        to="governance.group",
                    ),
                ),
                (
                    "proposed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="governance.membership",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mandate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        default=governance.models.new_mandate_reference,
                        max_length=12,
                        unique=True,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("payee_name", models.CharField(max_length=120)),
                ("payee_account", models.CharField(max_length=40)),
                (
                    "allocation",
                    models.CharField(
                        choices=[
                            (
                                "pro_rata",
                                "Shared by all members, in proportion to their balances",
                            ),
                            (
                                "member",
                                "Charged to one member (e.g. exit payout or loan)",
                            ),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("issued", "Issued"),
                            ("executed", "Executed"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="issued",
                        max_length=10,
                    ),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "executed_by_line_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mandates",
                        to="governance.fund",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mandates",
                        to="governance.group",
                    ),
                ),
                (
                    "charged_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="governance.membership",
                    ),
                ),
                (
                    "proposal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mandate",
                        to="governance.proposal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Approval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("approve", models.BooleanField()),
                ("source", models.CharField(default="app", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="governance.membership",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approvals",
                        to="governance.proposal",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="fund",
            constraint=models.UniqueConstraint(
                fields=("group", "name"), name="gov_fund_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="constitution",
            constraint=models.UniqueConstraint(
                fields=("group", "version"), name="gov_constitution_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("group", "person"),
                name="gov_one_active_membership",
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("group", "member_code"), name="gov_member_code_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="proposal",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="gov_proposal_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="proposal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("allocation", "member"), ("charged_member__isnull", False)
                    ),
                    models.Q(
                        ("allocation", "pro_rata"), ("charged_member__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="gov_proposal_allocation_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="mandate",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="gov_mandate_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="approval",
            constraint=models.UniqueConstraint(
                fields=("proposal", "membership"), name="gov_one_vote"
            ),
        ),
    ]
