# Generated by Django 5.2.17 on 2026-09-30 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("communities", "0001_initial"),
        ("governance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institution", models.CharField(max_length=40)),
                ("account_number", models.CharField(max_length=40)),
                ("account_name", models.CharField(max_length=120)),
                ("connector", models.CharField(max_length=40)),
                ("currency", models.CharField(default="KES", max_length=3)),
                ("linked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="communities.fund",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="communities.group",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PayerMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("msisdn", models.CharField(max_length=12)),
                ("confirmed_by", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="communities.group",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="communities.membership",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReconciliationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_at", models.DateTimeField(auto_now_add=True)),
                (
                    "statement_balance",
                    models.DecimalField(decimal_places=2, max_digits=18, null=True),
                ),
                ("ledger_cash", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "difference",
                    models.DecimalField(decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "member_interests",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("unattributed", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "unexplained_out",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("retained", models.DecimalField(decimal_places=2, max_digits=18)),
                ("lines_seen", models.PositiveIntegerField()),
                ("lines_unresolved", models.PositiveIntegerField()),
                ("sequence_gaps", models.JSONField(default=list)),
                ("open_alerts", models.PositiveIntegerField()),
                ("balanced", models.BooleanField()),
                (
                    "operation_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "external_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reconciliations",
                        to="custody.externalaccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StatementLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        help_text="The custodian's transaction id", max_length=64
                    ),
                ),
                (
                    "sequence",
                    models.BigIntegerField(help_text="The custodian's posting order"),
                ),
                ("posted_at", models.DateTimeField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("deposit", "deposit"),
                            ("withdrawal", "withdrawal"),
                            ("interest", "interest"),
                            ("charge", "charge"),
                            ("opening", "opening"),
                        ],
                        max_length=12,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("narration", models.CharField(blank=True, default="", max_length=255)),
                ("reference", models.CharField(blank=True, default="", max_length=64)),
                (
                    "counterparty_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "counterparty_msisdn",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "running_balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "external_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="custody.externalaccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LineResolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("attributed", "attributed"),
                            ("unattributed", "unattributed"),
                            ("interest", "interest"),
                            ("charge", "charge"),
                            ("matched", "matched"),
                            ("unmatched", "unmatched"),
                            ("explained", "explained"),
                            ("opening", "opening"),
                        ],
                        max_length=14,
                    ),
                ),
                ("journal_entry_id", models.BigIntegerField()),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("actor", models.CharField(default="system", max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mandate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="governance.mandate",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="communities.membership",
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resolutions",
                        to="custody.statementline",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            (
                                "unmatched_outflow",
                                "Money left without an approved mandate",
                            ),
                            ("recon_difference", "Books and custodian disagree"),
                            (
                                "statement_conflict",
                                "Custodian sent conflicting data for a transaction",
                            ),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolution_note",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="communities.group",
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="custody.statementline",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="externalaccount",
            constraint=models.UniqueConstraint(
                fields=("institution", "account_number"), name="custody_account_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="payermapping",
            constraint=models.UniqueConstraint(
                fields=("group", "msisdn"), name="custody_payer_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="statementline",
            index=models.Index(
                fields=["external_account", "sequence"],
                name="custody_sta_externa_784968_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="statementline",
            constraint=models.UniqueConstraint(
                fields=("external_account", "external_id"), name="custody_line_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="statementline",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="custody_line_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="alert",
            constraint=models.UniqueConstraint(
                condition=models.Q(("line__isnull", False)),
                fields=("kind", "line"),
                name="custody_one_alert_per_line",
            ),
        ),
    ]
