# Generated by Django 5.2.17 on 2026-09-30 12:31

import django.db.models.deletion
from django.db import migrations, models

from persistence.tenancy import tenant_scoped


class Migration(migrations.Migration):

    dependencies = [
        ("custody", "0002_append_only"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="externalaccount",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="lineresolution",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="payermapping",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="reconciliationrun",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="statementline",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
            ),
        ),
    ]


# Row-level security (ADR-0009): stamp tenant_id from context, force the policy.
Migration.operations += [migrations.RunSQL(*tenant_scoped(t)) for t in ('custody_externalaccount', 'custody_statementline', 'custody_lineresolution', 'custody_payermapping', 'custody_alert', 'custody_reconciliationrun')]
