# Generated by Django 5.2.17 on 2026-10-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custody", "0005_linked_rows_keep_their_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="reconciliationrun",
            name="balance_breaks",
            field=models.JSONField(default=list),
        ),
    ]
