# Generated by Django 5.2.17 on 2026-10-03 19:45

import django.db.models.deletion
from django.db import migrations, models

from persistence.postgres import append_only
from persistence.tenancy import platform_only


class Migration(migrations.Migration):

    dependencies = [
        ("custody", "0006_reconciliation_follows_the_running_balance"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institution", models.CharField(max_length=40)),
                ("account_number", models.CharField(max_length=40)),
                ("account_name", models.CharField(max_length=120)),
                ("connector", models.CharField(max_length=40)),
                ("currency", models.CharField(default="KES", max_length=3)),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("institution", "account_number"),
                        name="custody_collection_account_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=64)),
                ("sequence", models.BigIntegerField()),
                ("posted_at", models.DateTimeField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("deposit", "deposit"),
                            ("withdrawal", "withdrawal"),
                            ("interest", "interest"),
                            ("charge", "charge"),
                            ("opening", "opening"),
                        ],
                        max_length=12,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("narration", models.CharField(blank=True, default="", max_length=255)),
                ("reference", models.CharField(blank=True, default="", max_length=64)),
                (
                    "counterparty_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "counterparty_msisdn",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "running_balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collections",
                        to="custody.collectionaccount",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="externalaccount",
            name="pooled_in",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="custody.collectionaccount",
            ),
        ),
        migrations.CreateModel(
            name="CollectionRouting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("routed", "Routed to one fund's sub-account"),
                            ("held", "Held: belongs to no group yet"),
                        ],
                        max_length=8,
                    ),
                ),
                ("routed_to_tenant", models.BigIntegerField(blank=True, null=True)),
                ("external_account_id", models.BigIntegerField(blank=True, null=True)),
                ("sub_sequence", models.BigIntegerField(blank=True, null=True)),
                (
                    "sub_balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("actor", models.CharField(default="system", max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routings",
                        to="custody.collection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PoolAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("held", "A transaction belongs to no group yet"),
                            (
                                "conflict",
                                "The custodian resent a transaction with different details",
                            ),
                            (
                                "difference",
                                "The collection account and the groups' books disagree",
                            ),
                        ],
                        max_length=12,
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alerts",
                        to="custody.collectionaccount",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="custody.collection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PoolReconciliationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bank_balance",
                    models.DecimalField(decimal_places=2, max_digits=18, null=True),
                ),
                ("books_cash", models.DecimalField(decimal_places=2, max_digits=18)),
                ("held_net", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "difference",
                    models.DecimalField(decimal_places=2, max_digits=18, null=True),
                ),
                ("lines_seen", models.PositiveIntegerField()),
                ("sub_accounts", models.PositiveIntegerField()),
                ("sequence_gaps", models.JSONField(default=list)),
                ("balance_breaks", models.JSONField(default=list)),
                ("balanced", models.BooleanField()),
                (
                    "operation_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reconciliations",
                        to="custody.collectionaccount",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="collection",
            index=models.Index(
                fields=["account", "sequence"], name="custody_col_account_ba084a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="collection",
            constraint=models.UniqueConstraint(
                fields=("account", "external_id"), name="custody_collection_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="collection",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="custody_collection_amount_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="collectionrouting",
            index=models.Index(
                fields=["external_account_id", "sub_sequence"],
                name="custody_col_externa_99cc08_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionrouting",
            constraint=models.UniqueConstraint(
                condition=models.Q(("outcome", "routed")),
                fields=("collection",),
                name="custody_collection_routed_once",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionrouting",
            constraint=models.UniqueConstraint(
                condition=models.Q(("outcome", "routed")),
                fields=("external_account_id", "sub_sequence"),
                name="custody_sub_sequence_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionrouting",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("external_account_id__isnull", False),
                        ("outcome", "routed"),
                        ("routed_to_tenant__isnull", False),
                        ("sub_balance__isnull", False),
                        ("sub_sequence__isnull", False),
                    ),
                    models.Q(
                        ("external_account_id__isnull", True),
                        ("outcome", "held"),
                        ("routed_to_tenant__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="custody_routing_complete",
            ),
        ),
        migrations.AddConstraint(
            model_name="poolalert",
            constraint=models.UniqueConstraint(
                condition=models.Q(("collection__isnull", False)),
                fields=("kind", "collection"),
                name="custody_one_pool_alert_per_collection",
            ),
        ),
    ]

# Platform data about many tenants (ADR-0018): visible and writable only in a
# declared cross-tenant operation. The bank's facts, routing decisions and
# account-level runs are append-only, like statement lines.
PLATFORM = ("custody_collectionaccount", "custody_collection", "custody_collectionrouting", "custody_poolalert",
            "custody_poolreconciliationrun")
APPEND_ONLY = ("custody_collection", "custody_collectionrouting", "custody_poolreconciliationrun")
Migration.operations += [migrations.RunSQL(*platform_only(t)) for t in PLATFORM]
Migration.operations += [migrations.RunSQL(*append_only(t)) for t in APPEND_ONLY]
