# Generated by Django 5.2.17 on 2026-10-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custody", "0009_pay_in_moved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="kind",
            field=models.CharField(
                choices=[
                    ("unmatched_outflow", "Money left without an approved mandate"),
                    ("recon_difference", "Books and custodian disagree"),
                    (
                        "statement_conflict",
                        "Custodian sent conflicting data for a transaction",
                    ),
                    ("fund_code_unclear", "A pay-in's reference named no one fund"),
                ],
                max_length=20,
            ),
        ),
    ]
