# Generated by Django 5.2.17 on 2026-10-04 09:26

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Operator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=254, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("role", models.CharField(max_length=20)),
                ("active", models.BooleanField(default=True)),
                ("password", models.CharField(max_length=256)),
                ("must_change_password", models.BooleanField(default=True)),
                ("authenticator", models.BinaryField(null=True)),
                ("enrolled_at", models.DateTimeField(null=True)),
                ("last_code_step", models.BigIntegerField(null=True)),
                ("failed_attempts", models.PositiveSmallIntegerField(default=0)),
                ("locked_until", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("email", django.db.models.functions.text.Lower("email"))
                        ),
                        name="operators_email_lower_case",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OperatorEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=60)),
                ("actor", models.CharField(max_length=120)),
                ("data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="operators.operator",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OperatorSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("stage", models.CharField(max_length=20)),
                ("pending_authenticator", models.BinaryField(null=True)),
                ("created_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                ("step_up_at", models.DateTimeField(null=True)),
                ("ended_at", models.DateTimeField(null=True)),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="operators.operator",
                    ),
                ),
            ],
        ),
    ]
