# Generated by Django 5.2.17 on 2026-09-30 12:31

import django.db.models.deletion
from django.db import migrations, models

from persistence.tenancy import tenant_scoped


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0002_database_rules"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="journalline",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
            ),
        ),
    ]


# Row-level security (ADR-0009): stamp tenant_id from context, force the policy.
Migration.operations += [migrations.RunSQL(*tenant_scoped(t)) for t in ('ledger_account', 'ledger_journalentry', 'ledger_journalline')]

# The balance check runs deferred, at commit, when the tenant context that
# wrote the entry may already have ended. It reads the entry under the entry's
# own tenant, so row-level security can never hide its lines from the check.
TENANT_AWARE_BALANCE = """
CREATE OR REPLACE FUNCTION ledger_entry_must_balance() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    eid bigint;
    n integer;
    unbalanced integer;
    outer_tenant text := current_setting('app.tenant_id', true);
BEGIN
    IF TG_TABLE_NAME = 'ledger_journalentry' THEN eid := NEW.id; ELSE eid := NEW.entry_id; END IF;
    PERFORM set_config('app.tenant_id', NEW.tenant_id::text, true);
    SELECT count(*) INTO n FROM ledger_journalline WHERE entry_id = eid;
    IF n < 2 THEN
        RAISE EXCEPTION 'journal entry % has % line(s); at least 2 are required', eid, n
            USING ERRCODE = 'check_violation';
    END IF;
    SELECT count(*) INTO unbalanced FROM (
        SELECT a.currency
        FROM ledger_journalline l JOIN ledger_account a ON a.id = l.account_id
        WHERE l.entry_id = eid
        GROUP BY a.currency
        HAVING sum(CASE WHEN l.side = 'D' THEN l.amount ELSE -l.amount END) <> 0
    ) t;
    IF unbalanced > 0 THEN
        RAISE EXCEPTION 'journal entry % does not balance', eid USING ERRCODE = 'check_violation';
    END IF;
    PERFORM set_config('app.tenant_id', coalesce(outer_tenant, ''), true);
    RETURN NULL;
END $$;
"""
Migration.operations.append(migrations.RunSQL(TENANT_AWARE_BALANCE, migrations.RunSQL.noop))
