# Generated by Django 5.2.17 on 2026-09-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0003_tenant"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalentry",
            name="idempotency_key",
            field=models.CharField(max_length=160),
        ),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.UniqueConstraint(
                fields=("tenant", "idempotency_key"), name="ledger_entry_key_unique"
            ),
        ),
    ]
