# Generated by Django 5.2.17 on 2026-09-30 12:31

from django.db import migrations, models

from persistence.tenancy import DROP_FUNCTIONS, FUNCTIONS


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]


# The functions every tenant-scoped table's policy and stamp trigger use.
Migration.operations.append(migrations.RunSQL(FUNCTIONS, DROP_FUNCTIONS))
